version: '2'
volumes:
  database:

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432
  start_keycloak:
    image: dadarek/wait-for-dependencies
    depends_on:
      - keycloak
    command: keycloak:8080
  zap:
    image: owasp/zap2docker-weekly
    depends_on:
      - webui
    command: zap-baseline.py -t http://webui:2016
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - ./mailhog/maildir:/maildir
  keycloak:
    depends_on:
      - start_dependencies
    build:
      context: .
      dockerfile: ./keycloak/Dockerfile
    environment:
      - DB_DATABASE=mappamundi_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
    links:
      - db:postgres
      - mailhog
    volumes:
      - ./keycloak/themes/haven:/opt/jboss/keycloak/themes/haven
      - ./keycloak/data:/keycloak
    command: ["start-keycloak.sh", "-b", "0.0.0.0", "-Dkeycloak.migration.file=/keycloak/kuladodev-realm.json", "-Dkeycloak.migration.strategy=IGNORE_EXISTING", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.action=import"]
  flyway:
    build:
      context: flyway/
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db/mappamundi_dev
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_IGNORE_MISSING_MIGRATIONS=true
      - FLYWAY_GROUP=true
      - FLYWAY_SCHEMAS=mappa,1
      - FLYWAY_PLACEHOLDERS_DATABASEUSER=postgres
    command: ["migrate", "-placeholders.databaseUser=postgres"]
    links:
      - db
  apitest:
    build:
      context: .
      dockerfile: ./apitest/Dockerfile
    working_dir: /usr/src/app
    environment:
      - API_SERVER=api:8180
      - AUTH_SERVER=keycloak:8080
    volumes:
      - ./apitest:/usr/src/app
    links:
      - api
      - keycloak
    depends_on:
      - start_dependencies
    command: [cucumber]
  api:
    build:
      dockerfile: ./postgrest/Dockerfile
      context: .
    command: [postgrest, "/config"]
    environment:
      - DATABASE_NAME=mappamundi_dev
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - KULADO_JWK_PATH=/keycloak-dev-public-key.json
      - PGRST_JWT_AUD_CLAIM=kuladodev
      - PGRST_SERVER_PROXY_URI=http://localhost:8180
    volumes:
      - ./postgrest/keycloak-dev-public-key.json:/keycloak-dev-public-key.json
    ports:
      - "3001:8180"
    links:
      - db
    depends_on:
      - flyway
  swagger:
    image: havengrc-docker.jfrog.io/swaggerapi/swagger-ui:v3.0.2
    ports:
      - "3002:8080"
    volumes:
      - ./swagger/index.html:/usr/share/nginx/html/index.html
  db:
    image: postgres:9.6.4
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=mappamundi_dev
    volumes:
      - ./postgresql-data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user1@havengrc.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "8081:80"
  kuladoapi:
    working_dir: /go/src/github.com/kulado/wealthmind/kuladoapi
    volumes:
      - ./kuladoapi:/go/src/github.com/kulado/wealthmind/kuladoapi
      - /go/src/github.com/kulado/wealthmind/kuladoapi/vendor
      - ./postgrest/keycloak-dev-public-key.json:/keycloak-dev-public-key.json
    environment:
      - KULADO_JWK_PATH=/keycloak-dev-public-key.json
      - KC_ADMIN=admin
      - KC_PW=admin
      - KC_HOST=http://webui
      - KC_PORT=2016
    build:
      context: .
      dockerfile: ./kuladoapi/Dockerfile-hotreload
    links:
      - db
    ports:
      - "3000:3000"
  webui:
    working_dir: /code
    volumes:
      - ./webui:/code
      - /code/node_modules
    build:
      context: .
      dockerfile: ./webui/Dockerfile-hotreload
    links:
      - api
      - kuladoapi
      - keycloak
    ports:
      - "2015:2016"
    command: [/code/installrun.sh]
    environment:
      - ELM_APP_KEYCLOAK_CLIENT_ID=kuladodev
  docs:
    working_dir: /docs
    volumes:
      - ./docs:/docs
      - /docs/node_modules
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    ports:
      - "4000:4000"
    command: [serve]
  plantuml:
    working_dir: /docs
    volumes:
      - ./docs:/docs
    build:
      context: .
      dockerfile: ./docs/plantuml/Dockerfile
    command: [-v, /docs/plantuml/*.puml]
