FROM gobuffalo/buffalo:v0.12.4

RUN mkdir -p $GOPATH/src/github.com/kulado/wealthmind/kuladoapi
WORKDIR $GOPATH/src/github.com/kulado/wealthmind/kuladoapi
ADD ./kuladoapi/ $GOPATH/src/github.com/kulado/wealthmind/kuladoapi
RUN dep ensure

EXPOSE 3000
ENV ADDR 0.0.0.0
CMD exec buffalo dev
