---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: api
    spec:
      containers:
        - name: api
          image: kulado.azurecr.io/wealthmind/postgrest:latest
          args:
          - postgrest
          - /config
          env:
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_NAME
              value: "kuladostage"
            - name: PGRST_DB_SCHEMA
              value: "1"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kulado-database-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kulado-database-credentials
                  key: password
            - name: KULADO_JWK_PATH
              value: "/etc/kulado-credentials/jwk.json"
            - name: PGRST_JWT_AUD
              value: "kuladodev"
            - name: PGRST_JWT_SECRET
              value: "/kulado-credentials/jwk.json"
            - name: PGRST_SERVER_PORT
              value: "8180"
            - name: PGRST_SERVER_PROXY_URI
              value: "https://dashboard.wealthmind.net/api"
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/kulado-credentials/
              readOnly: true
          ports:
            - containerPort: 3001
              protocol: TCP
              targetPort: 8180
      volumes:
        - name: secret-volume
          secret:
            secretName: kulado-database-credentials
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
