---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: keycloak
    spec:
      containers:
        - name: keycloak
          image: kulado.azurecr.io/wealthmind/keycloak:4.0.0.Final
          env:
            - name: DB_DATABASE
              value: "kuladostage"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: kulado-database-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kulado-database-credentials
                  key: password
            - name: DB_ADDR
              value: "db"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kulado-database-credentials
                  key: password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              memory: 764Mi
            requests:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 75
            periodSeconds: 5
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
