apiVersion: v1
kind: Service
metadata:
  name: kuladoapi      
spec:
  selector:                  
    service: kuladoapi
  ports:
  - nodePort: 0
    port: 3000               
    protocol: TCP
    targetPort: 3000
