---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuladoweb
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: kuladoweb
    spec:
      containers:
        - name: kuladoweb
          image: kulado.azurecr.io/wealthmind/kuladoweb:latest
          env:
            - name: ELM_APP_KEYCLOAK_CLIENT_ID
              value: "kuladodev"
          ports:
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: /certs/
              readOnly: true
          resources:
              limits:
                memory: 256Mi
              requests:
                memory: 128Mi
      volumes:
        - name: secret-volume
          secret:
            secretName: kulado-tls
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
